//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSBANQUITO
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Telefono", Namespace="http://tempuri.org/")]
    public partial class Telefono : object
    {
        
        private int COD_TELField;
        
        private string NOMBREField;
        
        private decimal PRECIOField;
        
        private string FOTOField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int COD_TEL
        {
            get
            {
                return this.COD_TELField;
            }
            set
            {
                this.COD_TELField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NOMBRE
        {
            get
            {
                return this.NOMBREField;
            }
            set
            {
                this.NOMBREField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal PRECIO
        {
            get
            {
                return this.PRECIOField;
            }
            set
            {
                this.PRECIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FOTO
        {
            get
            {
                return this.FOTOField;
            }
            set
            {
                this.FOTOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerificarSujetoCreditoResult", Namespace="http://tempuri.org/")]
    public partial class VerificarSujetoCreditoResult : object
    {
        
        private bool EsSujetoCreditoField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool EsSujetoCredito
        {
            get
            {
                return this.EsSujetoCreditoField;
            }
            set
            {
                this.EsSujetoCreditoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalcularMontoMaximoCreditoResult", Namespace="http://tempuri.org/")]
    public partial class CalcularMontoMaximoCreditoResult : object
    {
        
        private double MontoMaximoCreditoField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double MontoMaximoCredito
        {
            get
            {
                return this.MontoMaximoCreditoField;
            }
            set
            {
                this.MontoMaximoCreditoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerCodigoClienteResult", Namespace="http://tempuri.org/")]
    public partial class ObtenerCodigoClienteResult : object
    {
        
        private System.Nullable<int> CodigoClienteField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> CodigoCliente
        {
            get
            {
                return this.CodigoClienteField;
            }
            set
            {
                this.CodigoClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amortizacion", Namespace="http://tempuri.org/")]
    public partial class Amortizacion : object
    {
        
        private int NumeroCuotaField;
        
        private decimal ValorCuotaField;
        
        private decimal InteresPagadoField;
        
        private decimal CapitalPagadoField;
        
        private decimal SaldoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumeroCuota
        {
            get
            {
                return this.NumeroCuotaField;
            }
            set
            {
                this.NumeroCuotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal ValorCuota
        {
            get
            {
                return this.ValorCuotaField;
            }
            set
            {
                this.ValorCuotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal InteresPagado
        {
            get
            {
                return this.InteresPagadoField;
            }
            set
            {
                this.InteresPagadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal CapitalPagado
        {
            get
            {
                return this.CapitalPagadoField;
            }
            set
            {
                this.CapitalPagadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Saldo
        {
            get
            {
                return this.SaldoField;
            }
            set
            {
                this.SaldoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrearFacturaResult", Namespace="http://tempuri.org/")]
    public partial class CrearFacturaResult : object
    {
        
        private string MensajeField;
        
        private int IdFacturaField;
        
        private decimal TotalFinalField;
        
        private int DescuentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int IdFactura
        {
            get
            {
                return this.IdFacturaField;
            }
            set
            {
                this.IdFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal TotalFinal
        {
            get
            {
                return this.TotalFinalField;
            }
            set
            {
                this.TotalFinalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Descuento
        {
            get
            {
                return this.DescuentoField;
            }
            set
            {
                this.DescuentoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://tempuri.org/")]
    public partial class Factura : object
    {
        
        private int IdFacturaField;
        
        private string NombreClienteField;
        
        private string CedulaField;
        
        private System.DateTime FechaField;
        
        private decimal TotalField;
        
        private string FormaPagoField;
        
        private int DescuentoField;
        
        private int CantidadField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdFactura
        {
            get
            {
                return this.IdFacturaField;
            }
            set
            {
                this.IdFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreCliente
        {
            get
            {
                return this.NombreClienteField;
            }
            set
            {
                this.NombreClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Cedula
        {
            get
            {
                return this.CedulaField;
            }
            set
            {
                this.CedulaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FormaPago
        {
            get
            {
                return this.FormaPagoField;
            }
            set
            {
                this.FormaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Descuento
        {
            get
            {
                return this.DescuentoField;
            }
            set
            {
                this.DescuentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSBANQUITO.WSBanquitoSoap")]
    public interface WSBanquitoSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarTelefono", ReplyAction="*")]
        System.Threading.Tasks.Task<WSBANQUITO.InsertarTelefonoResponse> InsertarTelefonoAsync(WSBANQUITO.InsertarTelefonoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTodosTelefonos", ReplyAction="*")]
        System.Threading.Tasks.Task<WSBANQUITO.ObtenerTodosTelefonosResponse> ObtenerTodosTelefonosAsync(WSBANQUITO.ObtenerTodosTelefonosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarTelefono", ReplyAction="*")]
        System.Threading.Tasks.Task<WSBANQUITO.ActualizarTelefonoResponse> ActualizarTelefonoAsync(WSBANQUITO.ActualizarTelefonoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarTelefono", ReplyAction="*")]
        System.Threading.Tasks.Task<WSBANQUITO.EliminarTelefonoResponse> EliminarTelefonoAsync(WSBANQUITO.EliminarTelefonoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarCredenciales", ReplyAction="*")]
        System.Threading.Tasks.Task<WSBANQUITO.ValidarCredencialesResponse> ValidarCredencialesAsync(WSBANQUITO.ValidarCredencialesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarSujetoCredito", ReplyAction="*")]
        System.Threading.Tasks.Task<WSBANQUITO.VerificarSujetoCreditoResponse> VerificarSujetoCreditoAsync(WSBANQUITO.VerificarSujetoCreditoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularMontoMaximoCredito", ReplyAction="*")]
        System.Threading.Tasks.Task<WSBANQUITO.CalcularMontoMaximoCreditoResponse> CalcularMontoMaximoCreditoAsync(WSBANQUITO.CalcularMontoMaximoCreditoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCodigoCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<WSBANQUITO.ObtenerCodigoClienteResponse> ObtenerCodigoClienteAsync(WSBANQUITO.ObtenerCodigoClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearTablaAmortizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<WSBANQUITO.CrearTablaAmortizacionResponse> CrearTablaAmortizacionAsync(WSBANQUITO.CrearTablaAmortizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTablaAmortizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<WSBANQUITO.ObtenerTablaAmortizacionResponse> ObtenerTablaAmortizacionAsync(WSBANQUITO.ObtenerTablaAmortizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<WSBANQUITO.CrearFacturaResponse> CrearFacturaAsync(WSBANQUITO.CrearFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerFacturas", ReplyAction="*")]
        System.Threading.Tasks.Task<WSBANQUITO.ObtenerFacturasResponse> ObtenerFacturasAsync(WSBANQUITO.ObtenerFacturasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarTelefonoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarTelefono", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.InsertarTelefonoRequestBody Body;
        
        public InsertarTelefonoRequest()
        {
        }
        
        public InsertarTelefonoRequest(WSBANQUITO.InsertarTelefonoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarTelefonoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal precio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string foto;
        
        public InsertarTelefonoRequestBody()
        {
        }
        
        public InsertarTelefonoRequestBody(string nombre, decimal precio, string foto)
        {
            this.nombre = nombre;
            this.precio = precio;
            this.foto = foto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarTelefonoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarTelefonoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.InsertarTelefonoResponseBody Body;
        
        public InsertarTelefonoResponse()
        {
        }
        
        public InsertarTelefonoResponse(WSBANQUITO.InsertarTelefonoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarTelefonoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarTelefonoResult;
        
        public InsertarTelefonoResponseBody()
        {
        }
        
        public InsertarTelefonoResponseBody(string InsertarTelefonoResult)
        {
            this.InsertarTelefonoResult = InsertarTelefonoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTodosTelefonosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTodosTelefonos", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.ObtenerTodosTelefonosRequestBody Body;
        
        public ObtenerTodosTelefonosRequest()
        {
        }
        
        public ObtenerTodosTelefonosRequest(WSBANQUITO.ObtenerTodosTelefonosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerTodosTelefonosRequestBody
    {
        
        public ObtenerTodosTelefonosRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTodosTelefonosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTodosTelefonosResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.ObtenerTodosTelefonosResponseBody Body;
        
        public ObtenerTodosTelefonosResponse()
        {
        }
        
        public ObtenerTodosTelefonosResponse(WSBANQUITO.ObtenerTodosTelefonosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerTodosTelefonosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSBANQUITO.Telefono[] ObtenerTodosTelefonosResult;
        
        public ObtenerTodosTelefonosResponseBody()
        {
        }
        
        public ObtenerTodosTelefonosResponseBody(WSBANQUITO.Telefono[] ObtenerTodosTelefonosResult)
        {
            this.ObtenerTodosTelefonosResult = ObtenerTodosTelefonosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarTelefonoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarTelefono", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.ActualizarTelefonoRequestBody Body;
        
        public ActualizarTelefonoRequest()
        {
        }
        
        public ActualizarTelefonoRequest(WSBANQUITO.ActualizarTelefonoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarTelefonoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codTel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal precio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string foto;
        
        public ActualizarTelefonoRequestBody()
        {
        }
        
        public ActualizarTelefonoRequestBody(int codTel, string nombre, decimal precio, string foto)
        {
            this.codTel = codTel;
            this.nombre = nombre;
            this.precio = precio;
            this.foto = foto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarTelefonoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarTelefonoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.ActualizarTelefonoResponseBody Body;
        
        public ActualizarTelefonoResponse()
        {
        }
        
        public ActualizarTelefonoResponse(WSBANQUITO.ActualizarTelefonoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarTelefonoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ActualizarTelefonoResult;
        
        public ActualizarTelefonoResponseBody()
        {
        }
        
        public ActualizarTelefonoResponseBody(string ActualizarTelefonoResult)
        {
            this.ActualizarTelefonoResult = ActualizarTelefonoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarTelefonoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarTelefono", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.EliminarTelefonoRequestBody Body;
        
        public EliminarTelefonoRequest()
        {
        }
        
        public EliminarTelefonoRequest(WSBANQUITO.EliminarTelefonoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarTelefonoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codTel;
        
        public EliminarTelefonoRequestBody()
        {
        }
        
        public EliminarTelefonoRequestBody(int codTel)
        {
            this.codTel = codTel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarTelefonoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarTelefonoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.EliminarTelefonoResponseBody Body;
        
        public EliminarTelefonoResponse()
        {
        }
        
        public EliminarTelefonoResponse(WSBANQUITO.EliminarTelefonoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarTelefonoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminarTelefonoResult;
        
        public EliminarTelefonoResponseBody()
        {
        }
        
        public EliminarTelefonoResponseBody(string EliminarTelefonoResult)
        {
            this.EliminarTelefonoResult = EliminarTelefonoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarCredencialesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarCredenciales", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.ValidarCredencialesRequestBody Body;
        
        public ValidarCredencialesRequest()
        {
        }
        
        public ValidarCredencialesRequest(WSBANQUITO.ValidarCredencialesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarCredencialesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public ValidarCredencialesRequestBody()
        {
        }
        
        public ValidarCredencialesRequestBody(string usuario, string contrasena)
        {
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarCredencialesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarCredencialesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.ValidarCredencialesResponseBody Body;
        
        public ValidarCredencialesResponse()
        {
        }
        
        public ValidarCredencialesResponse(WSBANQUITO.ValidarCredencialesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarCredencialesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidarCredencialesResult;
        
        public ValidarCredencialesResponseBody()
        {
        }
        
        public ValidarCredencialesResponseBody(bool ValidarCredencialesResult)
        {
            this.ValidarCredencialesResult = ValidarCredencialesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarSujetoCreditoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarSujetoCredito", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.VerificarSujetoCreditoRequestBody Body;
        
        public VerificarSujetoCreditoRequest()
        {
        }
        
        public VerificarSujetoCreditoRequest(WSBANQUITO.VerificarSujetoCreditoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarSujetoCreditoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula;
        
        public VerificarSujetoCreditoRequestBody()
        {
        }
        
        public VerificarSujetoCreditoRequestBody(string cedula)
        {
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarSujetoCreditoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarSujetoCreditoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.VerificarSujetoCreditoResponseBody Body;
        
        public VerificarSujetoCreditoResponse()
        {
        }
        
        public VerificarSujetoCreditoResponse(WSBANQUITO.VerificarSujetoCreditoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarSujetoCreditoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSBANQUITO.VerificarSujetoCreditoResult VerificarSujetoCreditoResult;
        
        public VerificarSujetoCreditoResponseBody()
        {
        }
        
        public VerificarSujetoCreditoResponseBody(WSBANQUITO.VerificarSujetoCreditoResult VerificarSujetoCreditoResult)
        {
            this.VerificarSujetoCreditoResult = VerificarSujetoCreditoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularMontoMaximoCreditoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularMontoMaximoCredito", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.CalcularMontoMaximoCreditoRequestBody Body;
        
        public CalcularMontoMaximoCreditoRequest()
        {
        }
        
        public CalcularMontoMaximoCreditoRequest(WSBANQUITO.CalcularMontoMaximoCreditoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcularMontoMaximoCreditoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codCliente;
        
        public CalcularMontoMaximoCreditoRequestBody()
        {
        }
        
        public CalcularMontoMaximoCreditoRequestBody(int codCliente)
        {
            this.codCliente = codCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularMontoMaximoCreditoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularMontoMaximoCreditoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.CalcularMontoMaximoCreditoResponseBody Body;
        
        public CalcularMontoMaximoCreditoResponse()
        {
        }
        
        public CalcularMontoMaximoCreditoResponse(WSBANQUITO.CalcularMontoMaximoCreditoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcularMontoMaximoCreditoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSBANQUITO.CalcularMontoMaximoCreditoResult CalcularMontoMaximoCreditoResult;
        
        public CalcularMontoMaximoCreditoResponseBody()
        {
        }
        
        public CalcularMontoMaximoCreditoResponseBody(WSBANQUITO.CalcularMontoMaximoCreditoResult CalcularMontoMaximoCreditoResult)
        {
            this.CalcularMontoMaximoCreditoResult = CalcularMontoMaximoCreditoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCodigoClienteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCodigoCliente", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.ObtenerCodigoClienteRequestBody Body;
        
        public ObtenerCodigoClienteRequest()
        {
        }
        
        public ObtenerCodigoClienteRequest(WSBANQUITO.ObtenerCodigoClienteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCodigoClienteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula;
        
        public ObtenerCodigoClienteRequestBody()
        {
        }
        
        public ObtenerCodigoClienteRequestBody(string cedula)
        {
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCodigoClienteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCodigoClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.ObtenerCodigoClienteResponseBody Body;
        
        public ObtenerCodigoClienteResponse()
        {
        }
        
        public ObtenerCodigoClienteResponse(WSBANQUITO.ObtenerCodigoClienteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCodigoClienteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSBANQUITO.ObtenerCodigoClienteResult ObtenerCodigoClienteResult;
        
        public ObtenerCodigoClienteResponseBody()
        {
        }
        
        public ObtenerCodigoClienteResponseBody(WSBANQUITO.ObtenerCodigoClienteResult ObtenerCodigoClienteResult)
        {
            this.ObtenerCodigoClienteResult = ObtenerCodigoClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearTablaAmortizacionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearTablaAmortizacion", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.CrearTablaAmortizacionRequestBody Body;
        
        public CrearTablaAmortizacionRequest()
        {
        }
        
        public CrearTablaAmortizacionRequest(WSBANQUITO.CrearTablaAmortizacionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearTablaAmortizacionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal valorPrestamo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int numCuotas;
        
        public CrearTablaAmortizacionRequestBody()
        {
        }
        
        public CrearTablaAmortizacionRequestBody(int codCliente, decimal valorPrestamo, int numCuotas)
        {
            this.codCliente = codCliente;
            this.valorPrestamo = valorPrestamo;
            this.numCuotas = numCuotas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearTablaAmortizacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearTablaAmortizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.CrearTablaAmortizacionResponseBody Body;
        
        public CrearTablaAmortizacionResponse()
        {
        }
        
        public CrearTablaAmortizacionResponse(WSBANQUITO.CrearTablaAmortizacionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearTablaAmortizacionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CrearTablaAmortizacionResult;
        
        public CrearTablaAmortizacionResponseBody()
        {
        }
        
        public CrearTablaAmortizacionResponseBody(string CrearTablaAmortizacionResult)
        {
            this.CrearTablaAmortizacionResult = CrearTablaAmortizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTablaAmortizacionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTablaAmortizacion", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.ObtenerTablaAmortizacionRequestBody Body;
        
        public ObtenerTablaAmortizacionRequest()
        {
        }
        
        public ObtenerTablaAmortizacionRequest(WSBANQUITO.ObtenerTablaAmortizacionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerTablaAmortizacionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codCliente;
        
        public ObtenerTablaAmortizacionRequestBody()
        {
        }
        
        public ObtenerTablaAmortizacionRequestBody(int codCliente)
        {
            this.codCliente = codCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTablaAmortizacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTablaAmortizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.ObtenerTablaAmortizacionResponseBody Body;
        
        public ObtenerTablaAmortizacionResponse()
        {
        }
        
        public ObtenerTablaAmortizacionResponse(WSBANQUITO.ObtenerTablaAmortizacionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerTablaAmortizacionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSBANQUITO.Amortizacion[] ObtenerTablaAmortizacionResult;
        
        public ObtenerTablaAmortizacionResponseBody()
        {
        }
        
        public ObtenerTablaAmortizacionResponseBody(WSBANQUITO.Amortizacion[] ObtenerTablaAmortizacionResult)
        {
            this.ObtenerTablaAmortizacionResult = ObtenerTablaAmortizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearFacturaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearFactura", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.CrearFacturaRequestBody Body;
        
        public CrearFacturaRequest()
        {
        }
        
        public CrearFacturaRequest(WSBANQUITO.CrearFacturaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearFacturaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal total;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string formaPago;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cantidad;
        
        public CrearFacturaRequestBody()
        {
        }
        
        public CrearFacturaRequestBody(int codCliente, decimal total, string formaPago, int cantidad)
        {
            this.codCliente = codCliente;
            this.total = total;
            this.formaPago = formaPago;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.CrearFacturaResponseBody Body;
        
        public CrearFacturaResponse()
        {
        }
        
        public CrearFacturaResponse(WSBANQUITO.CrearFacturaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearFacturaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSBANQUITO.CrearFacturaResult CrearFacturaResult;
        
        public CrearFacturaResponseBody()
        {
        }
        
        public CrearFacturaResponseBody(WSBANQUITO.CrearFacturaResult CrearFacturaResult)
        {
            this.CrearFacturaResult = CrearFacturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerFacturasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerFacturas", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.ObtenerFacturasRequestBody Body;
        
        public ObtenerFacturasRequest()
        {
        }
        
        public ObtenerFacturasRequest(WSBANQUITO.ObtenerFacturasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerFacturasRequestBody
    {
        
        public ObtenerFacturasRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerFacturasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerFacturasResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSBANQUITO.ObtenerFacturasResponseBody Body;
        
        public ObtenerFacturasResponse()
        {
        }
        
        public ObtenerFacturasResponse(WSBANQUITO.ObtenerFacturasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerFacturasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSBANQUITO.Factura[] ObtenerFacturasResult;
        
        public ObtenerFacturasResponseBody()
        {
        }
        
        public ObtenerFacturasResponseBody(WSBANQUITO.Factura[] ObtenerFacturasResult)
        {
            this.ObtenerFacturasResult = ObtenerFacturasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface WSBanquitoSoapChannel : WSBANQUITO.WSBanquitoSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class WSBanquitoSoapClient : System.ServiceModel.ClientBase<WSBANQUITO.WSBanquitoSoap>, WSBANQUITO.WSBanquitoSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSBanquitoSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSBanquitoSoapClient.GetBindingForEndpoint(endpointConfiguration), WSBanquitoSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSBanquitoSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSBanquitoSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSBanquitoSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSBanquitoSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSBanquitoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSBANQUITO.InsertarTelefonoResponse> WSBANQUITO.WSBanquitoSoap.InsertarTelefonoAsync(WSBANQUITO.InsertarTelefonoRequest request)
        {
            return base.Channel.InsertarTelefonoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSBANQUITO.InsertarTelefonoResponse> InsertarTelefonoAsync(string nombre, decimal precio, string foto)
        {
            WSBANQUITO.InsertarTelefonoRequest inValue = new WSBANQUITO.InsertarTelefonoRequest();
            inValue.Body = new WSBANQUITO.InsertarTelefonoRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.precio = precio;
            inValue.Body.foto = foto;
            return ((WSBANQUITO.WSBanquitoSoap)(this)).InsertarTelefonoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSBANQUITO.ObtenerTodosTelefonosResponse> WSBANQUITO.WSBanquitoSoap.ObtenerTodosTelefonosAsync(WSBANQUITO.ObtenerTodosTelefonosRequest request)
        {
            return base.Channel.ObtenerTodosTelefonosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSBANQUITO.ObtenerTodosTelefonosResponse> ObtenerTodosTelefonosAsync()
        {
            WSBANQUITO.ObtenerTodosTelefonosRequest inValue = new WSBANQUITO.ObtenerTodosTelefonosRequest();
            inValue.Body = new WSBANQUITO.ObtenerTodosTelefonosRequestBody();
            return ((WSBANQUITO.WSBanquitoSoap)(this)).ObtenerTodosTelefonosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSBANQUITO.ActualizarTelefonoResponse> WSBANQUITO.WSBanquitoSoap.ActualizarTelefonoAsync(WSBANQUITO.ActualizarTelefonoRequest request)
        {
            return base.Channel.ActualizarTelefonoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSBANQUITO.ActualizarTelefonoResponse> ActualizarTelefonoAsync(int codTel, string nombre, decimal precio, string foto)
        {
            WSBANQUITO.ActualizarTelefonoRequest inValue = new WSBANQUITO.ActualizarTelefonoRequest();
            inValue.Body = new WSBANQUITO.ActualizarTelefonoRequestBody();
            inValue.Body.codTel = codTel;
            inValue.Body.nombre = nombre;
            inValue.Body.precio = precio;
            inValue.Body.foto = foto;
            return ((WSBANQUITO.WSBanquitoSoap)(this)).ActualizarTelefonoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSBANQUITO.EliminarTelefonoResponse> WSBANQUITO.WSBanquitoSoap.EliminarTelefonoAsync(WSBANQUITO.EliminarTelefonoRequest request)
        {
            return base.Channel.EliminarTelefonoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSBANQUITO.EliminarTelefonoResponse> EliminarTelefonoAsync(int codTel)
        {
            WSBANQUITO.EliminarTelefonoRequest inValue = new WSBANQUITO.EliminarTelefonoRequest();
            inValue.Body = new WSBANQUITO.EliminarTelefonoRequestBody();
            inValue.Body.codTel = codTel;
            return ((WSBANQUITO.WSBanquitoSoap)(this)).EliminarTelefonoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSBANQUITO.ValidarCredencialesResponse> WSBANQUITO.WSBanquitoSoap.ValidarCredencialesAsync(WSBANQUITO.ValidarCredencialesRequest request)
        {
            return base.Channel.ValidarCredencialesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSBANQUITO.ValidarCredencialesResponse> ValidarCredencialesAsync(string usuario, string contrasena)
        {
            WSBANQUITO.ValidarCredencialesRequest inValue = new WSBANQUITO.ValidarCredencialesRequest();
            inValue.Body = new WSBANQUITO.ValidarCredencialesRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            return ((WSBANQUITO.WSBanquitoSoap)(this)).ValidarCredencialesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSBANQUITO.VerificarSujetoCreditoResponse> WSBANQUITO.WSBanquitoSoap.VerificarSujetoCreditoAsync(WSBANQUITO.VerificarSujetoCreditoRequest request)
        {
            return base.Channel.VerificarSujetoCreditoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSBANQUITO.VerificarSujetoCreditoResponse> VerificarSujetoCreditoAsync(string cedula)
        {
            WSBANQUITO.VerificarSujetoCreditoRequest inValue = new WSBANQUITO.VerificarSujetoCreditoRequest();
            inValue.Body = new WSBANQUITO.VerificarSujetoCreditoRequestBody();
            inValue.Body.cedula = cedula;
            return ((WSBANQUITO.WSBanquitoSoap)(this)).VerificarSujetoCreditoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSBANQUITO.CalcularMontoMaximoCreditoResponse> WSBANQUITO.WSBanquitoSoap.CalcularMontoMaximoCreditoAsync(WSBANQUITO.CalcularMontoMaximoCreditoRequest request)
        {
            return base.Channel.CalcularMontoMaximoCreditoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSBANQUITO.CalcularMontoMaximoCreditoResponse> CalcularMontoMaximoCreditoAsync(int codCliente)
        {
            WSBANQUITO.CalcularMontoMaximoCreditoRequest inValue = new WSBANQUITO.CalcularMontoMaximoCreditoRequest();
            inValue.Body = new WSBANQUITO.CalcularMontoMaximoCreditoRequestBody();
            inValue.Body.codCliente = codCliente;
            return ((WSBANQUITO.WSBanquitoSoap)(this)).CalcularMontoMaximoCreditoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSBANQUITO.ObtenerCodigoClienteResponse> WSBANQUITO.WSBanquitoSoap.ObtenerCodigoClienteAsync(WSBANQUITO.ObtenerCodigoClienteRequest request)
        {
            return base.Channel.ObtenerCodigoClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSBANQUITO.ObtenerCodigoClienteResponse> ObtenerCodigoClienteAsync(string cedula)
        {
            WSBANQUITO.ObtenerCodigoClienteRequest inValue = new WSBANQUITO.ObtenerCodigoClienteRequest();
            inValue.Body = new WSBANQUITO.ObtenerCodigoClienteRequestBody();
            inValue.Body.cedula = cedula;
            return ((WSBANQUITO.WSBanquitoSoap)(this)).ObtenerCodigoClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSBANQUITO.CrearTablaAmortizacionResponse> WSBANQUITO.WSBanquitoSoap.CrearTablaAmortizacionAsync(WSBANQUITO.CrearTablaAmortizacionRequest request)
        {
            return base.Channel.CrearTablaAmortizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSBANQUITO.CrearTablaAmortizacionResponse> CrearTablaAmortizacionAsync(int codCliente, decimal valorPrestamo, int numCuotas)
        {
            WSBANQUITO.CrearTablaAmortizacionRequest inValue = new WSBANQUITO.CrearTablaAmortizacionRequest();
            inValue.Body = new WSBANQUITO.CrearTablaAmortizacionRequestBody();
            inValue.Body.codCliente = codCliente;
            inValue.Body.valorPrestamo = valorPrestamo;
            inValue.Body.numCuotas = numCuotas;
            return ((WSBANQUITO.WSBanquitoSoap)(this)).CrearTablaAmortizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSBANQUITO.ObtenerTablaAmortizacionResponse> WSBANQUITO.WSBanquitoSoap.ObtenerTablaAmortizacionAsync(WSBANQUITO.ObtenerTablaAmortizacionRequest request)
        {
            return base.Channel.ObtenerTablaAmortizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSBANQUITO.ObtenerTablaAmortizacionResponse> ObtenerTablaAmortizacionAsync(int codCliente)
        {
            WSBANQUITO.ObtenerTablaAmortizacionRequest inValue = new WSBANQUITO.ObtenerTablaAmortizacionRequest();
            inValue.Body = new WSBANQUITO.ObtenerTablaAmortizacionRequestBody();
            inValue.Body.codCliente = codCliente;
            return ((WSBANQUITO.WSBanquitoSoap)(this)).ObtenerTablaAmortizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSBANQUITO.CrearFacturaResponse> WSBANQUITO.WSBanquitoSoap.CrearFacturaAsync(WSBANQUITO.CrearFacturaRequest request)
        {
            return base.Channel.CrearFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSBANQUITO.CrearFacturaResponse> CrearFacturaAsync(int codCliente, decimal total, string formaPago, int cantidad)
        {
            WSBANQUITO.CrearFacturaRequest inValue = new WSBANQUITO.CrearFacturaRequest();
            inValue.Body = new WSBANQUITO.CrearFacturaRequestBody();
            inValue.Body.codCliente = codCliente;
            inValue.Body.total = total;
            inValue.Body.formaPago = formaPago;
            inValue.Body.cantidad = cantidad;
            return ((WSBANQUITO.WSBanquitoSoap)(this)).CrearFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSBANQUITO.ObtenerFacturasResponse> WSBANQUITO.WSBanquitoSoap.ObtenerFacturasAsync(WSBANQUITO.ObtenerFacturasRequest request)
        {
            return base.Channel.ObtenerFacturasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSBANQUITO.ObtenerFacturasResponse> ObtenerFacturasAsync()
        {
            WSBANQUITO.ObtenerFacturasRequest inValue = new WSBANQUITO.ObtenerFacturasRequest();
            inValue.Body = new WSBANQUITO.ObtenerFacturasRequestBody();
            return ((WSBANQUITO.WSBanquitoSoap)(this)).ObtenerFacturasAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSBanquitoSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSBanquitoSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSBanquitoSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:887/Servicio/WSBanquito.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSBanquitoSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:887/Servicio/WSBanquito.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSBanquitoSoap,
            
            WSBanquitoSoap12,
        }
    }
}
